name: Package

on:
  release:
    types: [created]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    name: Build and Publish

    steps:

    - name: Checkout Respository
      uses: actions/checkout@v2

    - name: Setup NodeJS with Yarn Caching
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'
        scope: '@amnis'

    - name: Install NodeJS Dependencies
      run: yarn install

    - name: Lint for Code-Style Errors
      run: yarn lint

    - name: Run Unit Tests
      run: yarn test

    - name: Publish Packages
      run: yarn pub
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}